table 'GDP (millions of current international dollar) by country or  territory'
	lineageTag: 7af4b308-1318-4d2a-bece-d9a3b0d9a39c

	column 'Country Name'
		dataType: string
		lineageTag: 91efaea7-fad0-4bf4-84fe-dc3142bb72cd
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	column Forecast
		dataType: string
		lineageTag: 5dc8394a-b6dc-49a7-b488-09c1faee3982
		summarizeBy: none
		sourceColumn: Forecast

		annotation SummarizationSetBy = Automatic

	column 2025
		dataType: string
		lineageTag: 6bec1071-7cc9-4868-8dcd-60a097182cdd
		summarizeBy: none
		sourceColumn: 2025

		annotation SummarizationSetBy = Automatic

	column 2023
		dataType: int64
		formatString: 0
		lineageTag: 240ae4d3-da2d-475a-a1d0-709cf74b6dde
		summarizeBy: sum
		sourceColumn: 2023

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: d3cbda1f-63f2-4ac0-b1b4-083554bb3652
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'GDP (millions of current international dollar) by country or  territory' = m
		mode: import
		source =
				let
				    Source = Web.BrowserContents("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)"),
				    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5)"}, {"Column2", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5)"}, {"Column3", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5)"}, {"Column4", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4)"}, {"Column5", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(3), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3)"}, {"Column6", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(2) + TH[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2)"}, {"Column7", "TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(4) + TH[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(2) + TH[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=""2""]:not([rowspan]):nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(1), TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD[colspan=""2""]:not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(1)"}}, [RowSelector="TABLE.wikitable.sortable.sticky-header-multi.sort-under.static-row-numbers > * > TR"]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Table From Html",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Top Rows",null,"Country Name",Replacer.ReplaceValue,{"Column1"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Replaced Value", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country Name", type text}, {"Forecast", type text}, {"Year", type text}, {"Estimate", type text}, {"Year_1", type text}, {"Estimate_2", Int64.Type}, {"Year_3", type text}}),
				    #"Removed Top Rows1" = Table.Skip(#"Changed Type1",1),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Top Rows1",{"Year"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Estimate", "2025"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Year_1"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Estimate_2", "2023"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"Year_3"}),
				    #"Kept First Rows" = Table.FirstN(#"Removed Columns2",25),
				    #"Filtered Rows" = Table.SelectRows(#"Kept First Rows", each [2025] <> null and [2025] <> ""),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows","—","0",Replacer.ReplaceText,{"2025"}),
				    #"Added Index" = Table.AddIndexColumn(#"Replaced Value1", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Country Name", "Forecast", "2025", "2023"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

