table Orders
	lineageTag: d5f92e62-e1d6-4177-8f8d-9a789576ec2c

	column A`
		dataType: int64
		formatString: 0
		lineageTag: 9d750907-8c36-44ca-917f-cd601497a59d
		summarizeBy: sum
		sourceColumn: A`

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 82b86f22-87be-4325-b7bb-cbdaf3d89dc5
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 984fb32e-a31d-4a9f-840d-4d68f14fbf6e
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: ef4eea0d-7854-4986-bb23-70ef6fe51ff1
			defaultHierarchy: LocalDateTable_6dbd3069-f8e4-4032-b4fe-7630c84e5c8d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: int64
		formatString: 0
		lineageTag: cf9578bc-ea95-4614-a9ea-4b8f8fccdc68
		summarizeBy: sum
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 85d75a51-dd24-4a62-baf3-97e116d76c17
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2603bd14-5a25-44d2-866b-1d6475ee4ab1
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 44817d01-dd55-4518-9da0-1d56025c8258
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 4ae3de51-8fe2-43ae-b934-d0baaa1fa0e0
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 1ee61058-89c1-4abb-853f-7d66a6c91486
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: cddf8585-7bdb-4402-a69b-4c606e24c431
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 72263112-ff78-41eb-ab1a-2856fbcbbc03
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: cda7f009-bf5a-465d-b3d6-bff2cf90488b
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 789ef9ea-dc9e-4215-8aed-33ad471dbcd3
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: f2fc1d5e-14c5-4153-bfdd-b4e692572987
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1c8ab4ee-039a-4994-b42d-bc6535e42104
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 9132edbd-e7d9-400b-8677-bc4d77548830
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 65507f5b-cc2d-4c84-a1da-c58b384c8f8e
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: a8e1ab10-45de-4784-9818-2bd78c38e768
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 9f41a27c-5afe-4473-8ddd-13aff847968e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 4c3d4ac1-af27-46b6-9c0c-2c9bcd312634
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 560795dc-8493-4fd8-9a58-09ced60f2750
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\baps\Downloads\Data.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"A`", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", Int64.Type}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

